set -g prefix C-w
unbind C-b
bind C-w send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux conf"
set -g mouse on
set-option -ga terminal-overrides ',xterm-256color:Tc'
set -g set-clipboard on
set -g allow-passthrough on
set -g status-position top

# Use vim keybindings in copy mode
set-window-option -g mode-keys vi

# v for begin selection, y for copy
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle



# for lazydocker
# set-option -g default-command "newgrp docker; bash"
# set-hook -g after-new-session 'run-shell "newgrp docker"'
# set-option -g default-command "export DOCKER_HOST=unix:///var/run/docker.sock; bash"

# resolve ESC timelag
set -g escape-time 0

# pane operation
bind-key -T prefix x kill-pane

unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


# seamless between tmux and nvim
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"

## move pane
bind h if-shell "$is_vim" "send-keys C-w h"  "select-pane -L"
bind j if-shell "$is_vim" "send-keys C-w j"  "select-pane -D"
bind k if-shell "$is_vim" "send-keys C-w k"  "select-pane -U"
bind l if-shell "$is_vim" "send-keys C-w l"  "select-pane -R"

## resize pane
bind -n M-h if-shell "$is_vim" "send-keys M-h" "resize-pane -L 1"
bind -n M-j if-shell "$is_vim" "send-keys M-j" "resize-pane -D 1"
bind -n M-k if-shell "$is_vim" "send-keys M-k" "resize-pane -U 1"
bind -n M-l if-shell "$is_vim" "send-keys M-l" "resize-pane -R 1"

## swap pane

## close pane
bind x if-shell "$is_vim" "send-keys C-w x" "kill-pane"


# bind -n C-Down swap-pane -D
# bind -n C-Up   swap-pane -U

# window operation
# bind ] next-window
# bind [ previous-window

bind S swap-pane
bind J join-pane

# Highlight active pane border
set -g pane-active-border-style fg=blue,bg=darkblue
set -g pane-border-style fg=gray,bg=default

# pane border
set -g pane-border-lines double
set -g pane-border-indicators arrows
set -g pane-border-status off
